version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  zipkin:
    image: openzipkin/zipkin-gcp:latest
    environment:
      - STORAGE_TYPE=stackdriver
      - GOOGLE_APPLICATION_CREDENTIALS=/application_default_credentials.json
      - STACKDRIVER_PROJECT_ID=fc-it-cross-sbx-rev1
    volumes:
      - /Users/jamuriano/.config/gcloud/application_default_credentials.json:/application_default_credentials.json

  app:
    image: dev-telephonic:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - jaeger
    entrypoint: [ 'php', '-S', '0.0.0.0:8080', '-t', '/app/examples' ]
    volumes:
      - .:/app
      - /Users/jamuriano/.config/gcloud/application_default_credentials.json:/application_default_credentials.json
    working_dir: /app/examples
    ports:
      - "8080:8080"